### ISSUE TITLE
About training Generator

### ISSUE THREAD

**Issue by KN1GHT9** [Lihr747/CgtGAN#1]
Hello and congratulations on having your work accepted by 2023 ACM MM. One question for you, do you use traditional optimization methods or reinforcement learning algorithms while training the generators. Sorry, I don't seem to see an obvious reinforcement learning algorithm in the train function of CgtGan.py.

**Comment by JaireYu** [comment]
https://github.com/Lihr747/CgtGAN/blob/3ff6f94f3e660ac45a10b7e7fd77182fce421edc/cgtgan.py#L300
https://github.com/Lihr747/CgtGAN/blob/3ff6f94f3e660ac45a10b7e7fd77182fce421edc/cgtgan.py#L301
These two losses are CLIP loss provided by CLIP and naturalness loss provided by Discriminator. Both losses are calculated by Policy Gradient. They take the greedy search sequence, sampled sequences, their probs, and rewards as input. And give their policy gradient loss. For more details, you can refer to https://arxiv.org/abs/1612.00563.
