### ISSUE TITLE
Preprocessing step

### ISSUE THREAD

**Issue by hemanthsrisai963** [Lihr747/CgtGAN#5]
1.IN COCO annotations there is not train_caption json file 
![1](https://github.com/Lihr747/CgtGAN/assets/82597780/0cc376d6-2054-4313-bf80-5a03c2158e26)
I tried renaming captions_train2014 json file as train_caption json file and ran the command `python preprocess/coco/coco_train_images.py`
Got this error 
![error](https://github.com/Lihr747/CgtGAN/assets/82597780/68382b58-9e22-4386-8efe-7b2cfe174039)
Guide me through this process

**Comment by JaireYu** [comment]
@hemanthsrisai963 To reproduce, we recommend to use the COCO annotations we provide, which is split into train val and test. This split is also used in most research works.

**Comment by JaireYu** [comment]
It seems that there are problems with the google drive link. We already fixed it. Now you can access the json file through the link.
